version: "3.8"
services:
  tunnel:
    container_name: cloudflared-tunnel-dashy
    restart: unless-stopped
    image: cloudflare/cloudflared
    command: tunnel run
    environment:
      - TUNNEL_TOKEN=eyJhIjoiMGJlNjliODY5ZThhYjFiNzliZTI2MjY2YWQzODExOGEiLCJ0IjoiYWJjYjVjY2UtNjhjNi00ZDEwLThmNTQtZjIxYmViNDYyMDQ3IiwicyI6Ik1EWm1OR0kyTURrdFpqWmtZeTAwWlRNNUxUbGpNakV0Wm1Wa056STNORGhtTkdSaSJ9
  dashy:
    image: lissy93/dashy
    container_name: dashy
    volumes:
      - /NASshare/dashy/public/conf.yml:/app/public/conf.yml
      - /NASshare/dashy/public/icons:/app/public/item-icons/
    ports:
      - 8066:80
    # Set any environmental variables
    environment:
      - NODE_ENV=production
      - UID=1000
      - GID=1000
    restart: unless-stopped
    healthcheck:
      test: ['CMD', 'node', '/app/services/healthcheck']
      interval: 1m30s
      timeout: 10s
      retries: 3
      start_period: 40s