version: "3.8"
services:
  dashy:
    image: lissy93/dashy:latest
    container_name: dashy
    volumes:
      - /NAS/dashy/public/conf.yml:/app/public/conf.yml
      - /NAS/dashy/public/icons:/app/public/item-icons/
    ports:
      - 8066:8080
    # Set any environmental variables
    environment:
      - NODE_ENV=production
      - UID=1000
      - GID=1000
    restart: unless-stopped
    healthcheck:
      test: ['CMD', 'node', '/app/services/healthcheck']
      interval: 1m30s
      timeout: 10s
      retries: 3
      start_period: 40s
